### ISSUE TITLE
Consistent env_example files across all engines

### ISSUE THREAD

**Issue by atomikaya** [TiBillet/documentation_v2#2]

**Comment by Nasjoe** [comment]
Je dirais même plus : Un seul .env pour tous les gouverner, a mettre dans le dossier TDD.
On peut même aller plus loin : faire un script qui génère les variables...

**Comment by atomikaya** [comment]
Ben un seul env alors que tu veux que les moteurs puissent s'utiliser séparément bof non ? Après un script d'onboarding qu'on peut lancer après avoir clone pourquoi pas, c'est pas très compliqué à faire !

**Comment by Nasjoe** [comment]
Yes, je pensais à un seul env pour l'env de dev/test
Mais oui, en prod, c'est pas la même.
D'ailleurs, faudrait relire aussi la doc' sur la mise en prod. Les env' pourraient a aussi être simplifié ...

**Comment by atomikaya** [comment]
Yep. Dans la doc je suis en train de faire des grands tableaux qui seront ptet plus lisible que les commentaires dans le code, je pourrai faire ça pour la prod aussi :



![Image](https://github.com/user-attachments/assets/b60ece78-377e-4231-98df-31dc350b4520)
